before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
     - -s -w -X github.com/QuickBase/quickbase-cli/qbclient.Version={{.Version}}
    hooks:
      # post: upx -qqq -9 {{ .Path }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    homepage: https://github.com/QuickBase/quickbase-cli
    description: A Command Line Interface (CLI) to manage your Quickbase applications.
    folder: Formula
    license: "MIT"

    tap:
      owner: QuickBase
      name: homebrew-tap

    commit_author:
      name: qb-github-homebrew
      email: sregithubhomebrew@quickbase.com

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/QuickBase/quickbase-cli
    description: A Command Line Interface (CLI) to manage your Quickbase applications.
    maintainer: Quickbase <sregithubhomebrew@quickbase.com>
    license: MIT
    vendor: Quickbase
    formats:
    - apk
    - deb
    - rpm
